# Generated by Django 3.1.2 on 2020-10-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightings',
            name='indifferent',
            field=models.BooleanField(default=False, help_text='indifferent?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='age',
            field=models.CharField(blank=True, help_text='age: Adult? Juvenile? leave it blank if do not known', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='approaches',
            field=models.BooleanField(default=False, help_text='approaches?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='chasing',
            field=models.BooleanField(default=False, help_text='chasing?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='climbing',
            field=models.BooleanField(default=False, help_text='climbing?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='date',
            field=models.DateField(help_text='date'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='eating',
            field=models.BooleanField(default=False, help_text='eating?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='foraging',
            field=models.BooleanField(default=False, help_text='foraging?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='kuks',
            field=models.BooleanField(default=False, help_text='kuks?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='latitude',
            field=models.FloatField(help_text='latitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='location',
            field=models.CharField(blank=True, help_text='location: Above Ground? Ground Plane? leave it blank if do not known', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='longitude',
            field=models.FloatField(help_text='longitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='moans',
            field=models.BooleanField(default=False, help_text='moans?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='other_activities',
            field=models.CharField(blank=True, help_text='other_activities', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='primary_fur_color',
            field=models.CharField(blank=True, help_text='primary fur color: Gray? Cinnamon? Black? leave it blank if do not known', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='quaas',
            field=models.BooleanField(default=False, help_text='quaas?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='running',
            field=models.BooleanField(default=False, help_text='running?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='runs_from',
            field=models.BooleanField(default=False, help_text='runs from?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='shift',
            field=models.CharField(help_text='shift: AM? PM?', max_length=2),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='specific_location',
            field=models.CharField(blank=True, help_text='specific location, leave it blank if do not known', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='tail_flags',
            field=models.BooleanField(default=False, help_text='tail flags?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='tail_twitches',
            field=models.BooleanField(default=False, help_text='tail twitches?'),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='unique_squirrel_id',
            field=models.CharField(help_text='unique_squirrel_id', max_length=15),
        ),
    ]
