# Generated by Django 3.1.2 on 2020-10-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightings',
            name='specific_location',
        ),
        migrations.AddField(
            model_name='sightings',
            name='indifferent',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='sightings',
            name='specifi_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='age',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='approaches',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='chasing',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='climbing',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='eating',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='foraging',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='kuks',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='latitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='longitude',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='moans',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='other_activities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='primary_fur_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='quaas',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='running',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='runs_from',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='shift',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='tail_flags',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='tail_twitches',
            field=models.CharField(max_length=8),
        ),
    ]
